### ISSUE TITLE
ACE2 not merging with Ace2

### ISSUE THREAD

**Issue by motey** [covidgraph/graph-processing_text_gene_match#2] opened 2021-06-14 08:14 UTC
In the current [DEV](https://db-dev.covidgraph.org/browser/) version the normalization of `:Gene` names seems to be messed up.
Maybe it has to do with the renaming from `:GeneSymbol` to `:Gene` -> https://github.com/covidgraph/visual-graph-explorer/issues/51

See comment:
https://github.com/covidgraph/visual-graph-explorer/issues/51#issuecomment-860034677

**Comment by mpreusse** [comment] 2021-06-14 08:21
We have genes for human and mouse.

The genes have a property called taxid. That's a unique ID for the taxon a.k.a. the species. '9606' is human and '10090' is mouse.

We could add another filter to the queries to avoid additional complexity:

{g:Gene {type: 'symbol', taxid: '9606'})

**Comment by yGuy** [comment] 2021-06-14 08:35
> We have genes for human and mouse.

In the Covidgraph database? Is that useful? 
I am using the full text index to search for genes - I would have to do second level filtering to get rid of the mouse genes. Do we really *want* the mouse genes in the db?

**Comment by motey** [comment] 2021-06-14 08:51
@yGuy:
@jarasch had some meetings with scientiest at the DZD/Mouseclinic, culminating in an subproject. As a non scientiest, what i understand (veeery superficial and simply put); there are some very interesting questions and  informations you can potentially derive from matching human to mouse genes, and the existing research data, when researching diseases. 
So yes, this can make sense and we allready put some thoughts and work into this. If you are keen on dive deeper into this issue, we could make a call with @jarasch

**Comment by yGuy** [comment] 2021-06-14 11:05
Thanks for the explanation. No, I am not keen on diving deeper. I'm must a casual "user", with no background at all, and I was wondering why there is ACE2 and Ace2 and why they seem unrelated, because in the UI you can neither see that one is from a mouse and the other from a human and you cannot specify which one you want to see, either. 

So my thinking was: If this *was* a left-over from some data dump, we should get rid of it. But if it is something that researches find helpful, then how would you want to see this in the app: do you want the app to filter out all non-human genes (if so, what's the best way to do this in a full text query), or do you want the user to be able to specify the "taxon"? If yes, how?

I'm happy with the current state if you are. From my limited point of view, this seemed awkward.

**Comment by jarasch** [comment] 2021-06-14 11:27
@yGuy yes from a non-scientist perspective it looks awkward. But there's is difference between ACE2 and Ace2, namely human and mouse -> fullfilling the same function in the cell, unfortunately :-(

**Comment by yGuy** [comment] 2021-06-14 12:23
OK - closing this as "by design" - if case sensitivity is important, we might consider reworking or adjusting the search-indices, though.

**Closed as completed by yGuy** 2021-06-14 12:23 UTC
Labels: Type: Bug, Priority: Normal, Status: Clarification Needed, Status: In Dev

**Comment by mpreusse** [comment] 2021-06-16 12:57
We can also create an index for human only and search that.
